#! env /usr/bin/python3

import sys
import subprocess
import os

def _program(name, args):
    return subprocess.call([os.path.join(BIN_DIR, name)] + args)

def gringo(name):
    raise SystemExit(_program(name, sys.argv[1:]))

if __name__ == '__main__':
    BIN_DIR=os.path.join(os.path.dirname(__file__), "clingo")
    
    if sys.platform == "linux":
        BIN_DIR=os.path.join(BIN_DIR, 'linux')
        name='gringo'
    elif sys.platform == "darwin":
        BIN_DIR=os.path.join(BIN_DIR, 'darwin')
        name='gringo'
    elif sys.platform == "win32":
        BIN_DIR=os.path.join(BIN_DIR, 'win32')
        name='gringo.exe'

    sys.exit(gringo(name))
