#Planner Class Name
BFWS: 
  #Config parameters begin here
  #portfolio_planner is currently not implemented
  portfolio_planner: 
    help    : 'builds a portfolio portfolio planner based on config specs'
  argparse_module_path: 
    cmd_arg:  
      default : None #Leave empty if default lapkt.py module suffices
      required: False
      nargs   : '?'
      action  : 'store'
      help    : 'python module for parsing cmd args and running solver'
  # Use this as example config
  log_file: 
  # cmd_args will be loaded in ArgumentParser python module
    cmd_arg: 
      default : 'log' #
      required: False
      nargs   : '?'
      action  : 'store'
      help    : 'log file name'
    # 'var_name' is the name of interface (in module.cxx) 
    #     via which a config value is stored into cpp variable.
    # 'fun_name' is the name of a setter (in module.cxx) 
    #     which pushes exactly 1 (String/numeric) value.
    var_name: 'log_filename'   
  plan_file: 
    cmd_arg: 
      default: 'plan.ipc' #
      required: False
      nargs   : '?'
      action  : 'store'
      help    : 'file name where solution plan will be stored'
    var_name: 'plan_filename'
  search_type: 
    cmd_arg: 
      default: 'DUAL-BFWS' #
      required: False
      choices:
        - 'BFWS-f5-landmarks'
        - 'BFWS-goalcount-only'
        - 'BFWS-f5'
        - 'BFWS-f5-initstate-relevant'
        - 'k-BFWS'
        - 'k-M-BFWS'
        - 'k-M-C-BFWS'
        - 'k-C-BFWS'
        - '1-C-BFWS'
        - '1-BFWS'
        - 'POLY-BFWS'
        - 'DUAL-C-BFWS'
        - 'DUAL-BFWS'
      nargs   : '?'
      action  : 'store'
      help    : "specify a variant of BFWS - default 'DUAL-BFWS'"
    var_name: 'search'
  anytime: 
    cmd_arg: 
      default : False
      required: False
      action  : 'store_true'
      help    : 'enable anytime planning'
    var_name: 'anytime'
  max_novelty:  
    cmd_arg: 
      default: 2
      required: False
      nargs   : '?'
      type    : 'int'
      action  : 'store'
      help    : 'Max bound for novelty computation'
    var_name: 'max_novelty'
  m_value:  
    cmd_arg: 
      default: 32
      required: False
      nargs   : '?'
      type    : 'int'
      action  : 'store'
      help    : 'For M-variants of BFWS, increases the number of expanded nodes by the constant factor.'
    var_name: 'm_value'

#END - Leave this line a empty line as it is
