(define (problem p5-3-10-tiny-network-0)
(:domain data-network)
(:objects
    data-0-3 data-0-5 data-1-2 data-1-4 data-2-1 - data
    script1 script2 script3 script4 script5 script6 script7 script8 script9 script10 - script
    server1 server2 server3 - server
    number0 number1 number2 number3 number4 number5 number6 number7 number8 number9 number10 number11 number12 number13 number14 number15 number16 - numbers
)
(:init
    (script-io script1 data-0-3 data-0-5 data-1-4)
    (script-io script2 data-0-5 data-0-3 data-1-2)
    (script-io script3 data-1-4 data-0-5 data-2-1)
    (script-io script4 data-0-3 data-0-5 data-1-4)
    (script-io script5 data-1-2 data-0-5 data-2-1)
    (script-io script6 data-1-2 data-0-3 data-2-1)
    (script-io script7 data-0-5 data-0-3 data-1-2)
    (script-io script8 data-1-4 data-1-2 data-2-1)
    (script-io script9 data-0-3 data-0-5 data-1-4)
    (script-io script10 data-1-2 data-1-4 data-2-1)
    (connected server1 server2)
    (connected server2 server1)
    (connected server1 server3)
    (connected server3 server1)
    (data-size data-0-3 number4)
    (data-size data-0-5 number5)
    (data-size data-1-2 number4)
    (data-size data-1-4 number1)
    (data-size data-2-1 number4)
    (capacity server1 number16)
    (capacity server2 number8)
    (capacity server3 number8)
    (sum number0 number1 number1)
    (sum number0 number4 number4)
    (sum number0 number5 number5)
    (sum number1 number1 number2)
    (sum number1 number4 number5)
    (sum number1 number5 number6)
    (sum number2 number1 number3)
    (sum number2 number4 number6)
    (sum number2 number5 number7)
    (sum number3 number1 number4)
    (sum number3 number4 number7)
    (sum number3 number5 number8)
    (sum number4 number1 number5)
    (sum number4 number4 number8)
    (sum number4 number5 number9)
    (sum number5 number1 number6)
    (sum number5 number4 number9)
    (sum number5 number5 number10)
    (sum number6 number1 number7)
    (sum number6 number4 number10)
    (sum number6 number5 number11)
    (sum number7 number1 number8)
    (sum number7 number4 number11)
    (sum number7 number5 number12)
    (sum number8 number1 number9)
    (sum number8 number4 number12)
    (sum number8 number5 number13)
    (sum number9 number1 number10)
    (sum number9 number4 number13)
    (sum number9 number5 number14)
    (sum number10 number1 number11)
    (sum number10 number4 number14)
    (sum number10 number5 number15)
    (sum number11 number1 number12)
    (sum number11 number4 number15)
    (sum number11 number5 number16)
    (sum number12 number1 number13)
    (sum number12 number4 number16)
    (sum number13 number1 number14)
    (sum number14 number1 number15)
    (sum number15 number1 number16)
    (less-equal number1 number8)
    (less-equal number1 number16)
    (less-equal number2 number8)
    (less-equal number2 number16)
    (less-equal number3 number8)
    (less-equal number3 number16)
    (less-equal number4 number8)
    (less-equal number4 number16)
    (less-equal number5 number8)
    (less-equal number5 number16)
    (less-equal number6 number8)
    (less-equal number6 number16)
    (less-equal number7 number8)
    (less-equal number7 number16)
    (less-equal number8 number8)
    (less-equal number8 number16)
    (less-equal number9 number16)
    (less-equal number10 number16)
    (less-equal number11 number16)
    (less-equal number12 number16)
    (less-equal number13 number16)
    (less-equal number14 number16)
    (less-equal number15 number16)
    (less-equal number16 number16)
    (= (total-cost) 0)
    (= (process-cost script1 server1) 16)
    (= (process-cost script1 server2) 11)
    (= (process-cost script1 server3) 9)
    (= (process-cost script2 server1) 22)
    (= (process-cost script2 server2) 11)
    (= (process-cost script2 server3) 10)
    (= (process-cost script3 server1) 16)
    (= (process-cost script3 server2) 10)
    (= (process-cost script3 server3) 10)
    (= (process-cost script4 server1) 26)
    (= (process-cost script4 server2) 9)
    (= (process-cost script4 server3) 8)
    (= (process-cost script5 server1) 26)
    (= (process-cost script5 server2) 8)
    (= (process-cost script5 server3) 6)
    (= (process-cost script6 server1) 20)
    (= (process-cost script6 server2) 7)
    (= (process-cost script6 server3) 11)
    (= (process-cost script7 server1) 19)
    (= (process-cost script7 server2) 9)
    (= (process-cost script7 server3) 10)
    (= (process-cost script8 server1) 18)
    (= (process-cost script8 server2) 7)
    (= (process-cost script8 server3) 6)
    (= (process-cost script9 server1) 18)
    (= (process-cost script9 server2) 10)
    (= (process-cost script9 server3) 13)
    (= (process-cost script10 server1) 22)
    (= (process-cost script10 server2) 8)
    (= (process-cost script10 server3) 12)
    (= (send-cost server1 server2 number1) 4)
    (= (send-cost server2 server1 number1) 4)
    (= (send-cost server1 server2 number4) 16)
    (= (send-cost server2 server1 number4) 16)
    (= (send-cost server1 server2 number5) 20)
    (= (send-cost server2 server1 number5) 20)
    (= (send-cost server1 server3 number1) 6)
    (= (send-cost server3 server1 number1) 6)
    (= (send-cost server1 server3 number4) 24)
    (= (send-cost server3 server1 number4) 24)
    (= (send-cost server1 server3 number5) 30)
    (= (send-cost server3 server1 number5) 30)
    (= (io-cost server1 number1) 5)
    (= (io-cost server1 number4) 20)
    (= (io-cost server1 number5) 25)
    (= (io-cost server2 number1) 1)
    (= (io-cost server2 number4) 4)
    (= (io-cost server2 number5) 5)
    (= (io-cost server3 number1) 1)
    (= (io-cost server3 number4) 4)
    (= (io-cost server3 number5) 5)
    (saved data-0-3 server3)
    (saved data-0-5 server1)
    (usage server1 number0)
    (usage server2 number0)
    (usage server3 number0)
)
(:goal
(and
    (saved data-2-1 server2)
)
)
(:metric minimize (total-cost))
)