# About: Configuration for run_experiment.py
# These configuration will be overridden by corresponding command line args.

# Paths must be specified either as absolute paths or relative to 'run_experiments.py'

SOLVERS: # must be specified as a list of executables with necessary args
    - '../release/lapkt.py AT_LAPKT_Planner'
    - '../release/lapkt.py AT_BFS_f_Planner'
    - '../release/lapkt.py BFS_f_Planner'
    - '../release/lapkt.py BRFS_Planner'
    - '../release/lapkt.py DFIW_Planner'
    - '../release/lapkt.py DFSIW_Planner'
    - '../release/lapkt.py DFS_Plus_Planner'
    - '../release/lapkt.py IW_Planner'
    - '../release/lapkt.py RPIW_Planner'
    - '../release/lapkt.py SIW_Planner'
    - '../release/lapkt.py SIW_Plus_Planner'
    - '../release/lapkt.py SIW_PLUS_BFS_F_Planner'
NUM_PROC: null #null->use all cpus
#PLIST_YML is the path to the yml file with pddl problem database
PLIST_YML: '../pddl_domains_repo/classical_fixed/plist.yml' # path must be specified
BNAME: null # null->All benchmarks
DNAME: # null->All domains
  - 'visitall' 
PNAME: null # null->All instances
PLAN_FILE: 'plan.ipc' # name must be specified
# if a problem in PLIST_YML no tag assigned then it is NOT filtered out
#   and TAGS setting below has no effect
TAGS: # null->All(no filtering on TAGs)
  - 'OPT' 
VALIDATE: '/home/simhasama/Github/anubhav-gres/width-based-algos-LAPKT/LAPKT-public_port/release/bin/validate' # null->No validation
EXP_DIR: './data' # path to output dir must be specified
EXP_NAME: 'Classical_Runs' # string must be specified
TIME_LIMIT: 5 #seconds
MEMORY_LIMIT: 2048 #MB
