import os

debug = ARGUMENTS.get('debug', 0)

env = Environment()

include_paths = ['../../include', '.']
lib_paths = [ '../..' ]
libs = ['aptk',]


env.Append( LIBPATH = [ '/usr/lib' ] )
env.Append( CPPPATH = [ os.path.abspath(p) for p in include_paths ] )
env.Append( CCFLAGS = [ '-std=c++11', '-fPIC' ] )
if int(debug) == 1 :
	env.Append( CCFLAGS = ['-g', '-DDEBUG' ] )
else:
	env.Append( CCFLAGS = ['-O3', '-DNDEBUG'] )

env.Append( LIBS=libs)
env.Append( LIBPATH=[ os.path.abspath(p) for p in lib_paths ] )

cxx_sources = Glob('*.cxx')
c_sources = Glob('*.c')
objects = [ env.Object(s) for s in cxx_sources ] + [ env.Object(s) for s in c_sources ]

env.Library( 'aptk-base', objects )
