; compilation cpu-time: 0.000 seconds
(define (problem grounded-strips-os-sequencedstrips-small-4)
(:domain grounded-strips-openstacks-sequencedstrips)
(:init
(not-made-p1)
(not-made-p2)
(not-made-p3)
(not-made-p4)
(not-made-p5)
(waiting-o5)
(waiting-o4)
(waiting-o3)
(waiting-o2)
(waiting-o1)
(stacks-avail-n0)
(machine-available-)
)
(:goal
(and
(shipped-o5)
(shipped-o4)
(shipped-o3)
(shipped-o2)
(shipped-o1)
)
)
)
