import os
Import('common_env')

include_paths = ['.', '/usr/include/python2.7' ]
common_env.Append( CPPPATH = [ os.path.abspath(p) for p in include_paths ] )

# Python and Boost.Python settings

common_env.Append( CCFLAGS = '-fPIC' )
common_env.Append( LIBS = [ '-lboost_python', '-lpython2.7' ] )
common_env.Append( LIBPATH = [ '/usr/lib/python2.7/config' ] )
common_env['STATIC_AND_SHARED_OBJECTS_ARE_THE_SAME']=1

cxx_sources = Glob('*.cxx')
c_sources = Glob('*.c')

objects = [ common_env.Object(s) for s in cxx_sources ] + [ common_env.Object(s) for s in c_sources ]

Return('objects')
