import os
Import('common_env')
env = common_env.Clone()

cxx_sources = Glob('*.cxx')
c_sources = Glob('*.c')

objects = [ env.Object(s) for s in cxx_sources ] + [ env.Object(s) for s in c_sources ]

Return('objects')
