import os

debug = ARGUMENTS.get( 'debug', 0 )
common_env = Environment()

common_env.Append( CCFLAGS = [ '-Wall', '-std=c++0x' ] )

if int(debug) == 1 :
        common_env.Append( CCFLAGS = ['-g',  '-DDEBUG' ] )
else:
        common_env.Append( CCFLAGS = ['-O3', '-DNDEBUG'] )

Export( 'common_env' )

model_objs = SConscript('../../../models/fodet/SConscript')
heuristics_objs = SConscript('../../../heuristics/fodet/SConscript')
tools_objs = SConscript('../../../tools/SConscript')
python_objs = SConscript('../../../python/fodet/SConscript')
example_objs = SConscript('src/SConscript')

common_env.SharedLibrary( 'aptk.so', example_objs + heuristics_objs + model_objs + python_objs + tools_objs  ) 
